name 'rharrison-bacula'
version '0.5.1'

author 'Puppet Labs and Russell Harrison'
license 'ASL 2.0'
project_page 'http://github.com/rharrison10/rharrison-bacula'
source 'http://github.com/rharrison10/rharrison-bacula'
summary 'This module manages a bacula infrastructure'
description 'This module manages Bacula, a complete backup solution.'
dependency 'puppetlabs/stdlib', '>=2.2.0'
dependency 'puppetlabs-mysql', '>=1.0.0'
dependency 'puppetlabs/sqlite', '>=0.0.1'
